# Generated by Django 4.2.7 on 2025-09-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='itle',
            new_name='title',
        ),
    ]
