# Generated by Django 4.2.7 on 2025-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250919_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='advanced_features_used',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_type',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='enhanced_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='original_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='scene_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='unique_objects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
