# Generated by Django 4.2.7 on 2025-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_advanced_features_used_video_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_json_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
