# Generated by Django 4.2.7 on 2025-09-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_analysis_json_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.IntegerField()),
                ('timestamp', models.FloatField(default=0.0)),
                ('persons_detected', models.JSONField(blank=True, default=list)),
                ('scene_analysis', models.JSONField(blank=True, default=dict)),
                ('quality_metrics', models.JSONField(blank=True, default=dict)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='api.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'frame_id'], name='api_analysi_video_i_2d7ec4_idx')],
                'unique_together': {('video', 'frame_id')},
            },
        ),
    ]
