# Generated by Django 4.2.7 on 2025-09-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=0)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('bbox_x1', models.FloatField(default=0.0)),
                ('bbox_y1', models.FloatField(default=0.0)),
                ('bbox_x2', models.FloatField(default=0.0)),
                ('bbox_y2', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('gender_estimation', models.CharField(default='unknown', max_length=50)),
                ('gender_confidence', models.FloatField(default=0.0)),
                ('age_group', models.CharField(default='unknown', max_length=50)),
                ('age_confidence', models.FloatField(default=0.0)),
                ('upper_body_color', models.CharField(default='unknown', max_length=50)),
                ('upper_color_confidence', models.FloatField(default=0.0)),
                ('lower_body_color', models.CharField(default='unknown', max_length=50)),
                ('lower_color_confidence', models.FloatField(default=0.0)),
                ('posture', models.CharField(default='unknown', max_length=50)),
                ('posture_confidence', models.FloatField(default=0.0)),
                ('detailed_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_detections', to='api.frame')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_detections', to='api.video')),
            ],
        ),
        migrations.CreateModel(
            name='YOLOObjectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField(default=0.0)),
                ('class_name', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yolo_detections', to='api.frame')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolo_detections', to='api.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'frame_number', 'class_name'], name='api_yoloobj_video_i_220f6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_color', models.CharField(blank=True, max_length=50, null=True)),
                ('clothing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('posture', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('person_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persondetection')),
            ],
            options={
                'indexes': [models.Index(fields=['clothing_color'], name='api_persons_clothin_c06d52_idx'), models.Index(fields=['clothing_type'], name='api_persons_clothin_490174_idx'), models.Index(fields=['posture'], name='api_persons_posture_edbd5a_idx'), models.Index(fields=['gender'], name='api_persons_gender_5ac7d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='persondetection',
            index=models.Index(fields=['video', 'person_id'], name='api_persond_video_i_3b9f6d_idx'),
        ),
    ]
