# Generated by Django 4.2.7 on 2025-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_persondetection_yoloobjectdetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='comprehensive_features',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='enhanced_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='final_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
