# Generated by Django 4.2.18 on 2025-09-29 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(help_text='영상 ID', unique=True)),
                ('analysis_data', models.JSONField(default=dict, help_text='영상 분석 결과')),
                ('analysis_summary', models.TextField(blank=True, help_text='분석 결과 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '영상 분석 캐시',
                'verbose_name_plural': '영상 분석 캐시들',
            },
        ),
        migrations.CreateModel(
            name='VideoChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.IntegerField(help_text='영상 ID (backend_videochat의 Video 모델과 연결)')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_analysis_data', models.JSONField(blank=True, default=dict, help_text='영상 분석 결과 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '영상 채팅 세션',
                'verbose_name_plural': '영상 채팅 세션들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', '사용자'), ('ai_individual', 'AI 개별 응답'), ('ai_optimal', 'AI 통합 응답'), ('system', '시스템')], max_length=20)),
                ('content', models.TextField()),
                ('ai_model', models.CharField(blank=True, help_text='AI 모델명 (gpt, claude, mixtral 등)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.ForeignKey(blank=True, help_text='통합 응답의 경우 원본 개별 응답들을 참조', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='chat.videochatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.videochatsession')),
            ],
            options={
                'verbose_name': '영상 채팅 메시지',
                'verbose_name_plural': '영상 채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
    ]
