# Generated by Django 4.2.18 on 2025-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_videoanalysiscache_videochatsession_videochatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('filename', models.CharField(default='', max_length=255)),
                ('original_name', models.CharField(default='', max_length=255)),
                ('file_path', models.CharField(default='', max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_status', models.CharField(default='pending', max_length=50)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('duration', models.FloatField(default=0.0)),
                ('enhanced_analysis', models.BooleanField(default=False)),
                ('success_rate', models.FloatField(default=0.0)),
                ('processing_time', models.IntegerField(default=0)),
                ('analysis_type', models.CharField(default='basic', max_length=50)),
                ('advanced_features_used', models.JSONField(blank=True, default=dict)),
                ('scene_types', models.JSONField(blank=True, default=list)),
                ('unique_objects', models.IntegerField(default=0)),
                ('analysis_json_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상들',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
