# Generated by Django 4.2.18 on 2025-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_message',
            field=models.CharField(blank=True, help_text='분석 진행 메시지', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_progress',
            field=models.IntegerField(default=0, help_text='분석 진행률 (0-100)'),
        ),
    ]
