# Generated by Django 4.2.18 on 2025-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_video_analysis_message_video_analysis_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_images_path',
            field=models.CharField(blank=True, help_text='프레임 이미지 저장 경로', max_length=500, null=True),
        ),
    ]
