# Generated by Django 4.2.18 on 2025-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_video_frame_images_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='activity_patterns',
            field=models.JSONField(blank=True, default=dict, help_text='활동 패턴'),
        ),
        migrations.AddField(
            model_name='video',
            name='age_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='나이대 분포'),
        ),
        migrations.AddField(
            model_name='video',
            name='detected_objects',
            field=models.JSONField(blank=True, default=list, help_text='감지된 객체들 (car, person, sign, etc.)'),
        ),
        migrations.AddField(
            model_name='video',
            name='gender_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='성별 분포'),
        ),
        migrations.AddField(
            model_name='video',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='주요 이벤트 하이라이트'),
        ),
        migrations.AddField(
            model_name='video',
            name='hourly_statistics',
            field=models.JSONField(blank=True, default=dict, help_text='시간대별 통계'),
        ),
        migrations.AddField(
            model_name='video',
            name='key_events',
            field=models.JSONField(blank=True, default=list, help_text='주요 이벤트 타임스탬프'),
        ),
        migrations.AddField(
            model_name='video',
            name='lighting_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='조명 조건 (bright, normal, dark, artificial)'),
        ),
        migrations.AddField(
            model_name='video',
            name='location_type',
            field=models.CharField(blank=True, help_text='위치 유형', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='object_statistics',
            field=models.JSONField(blank=True, default=dict, help_text='객체별 통계'),
        ),
        migrations.AddField(
            model_name='video',
            name='person_demographics',
            field=models.JSONField(blank=True, default=dict, help_text='사람 인구통계 (gender, age, clothing)'),
        ),
        migrations.AddField(
            model_name='video',
            name='scene_context',
            field=models.JSONField(blank=True, default=dict, help_text='장면 맥락 (indoor, outdoor, street, building)'),
        ),
        migrations.AddField(
            model_name='video',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list, help_text='검색 키워드'),
        ),
        migrations.AddField(
            model_name='video',
            name='search_tags',
            field=models.JSONField(blank=True, default=list, help_text='검색 태그'),
        ),
        migrations.AddField(
            model_name='video',
            name='time_of_day',
            field=models.CharField(blank=True, help_text='시간대 (morning, afternoon, evening, night)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_summary',
            field=models.TextField(blank=True, help_text='영상 요약', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='weather_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='날씨 조건 (rain, snow, sunny, cloudy)'),
        ),
    ]
