# Generated by Django 4.2.18 on 2025-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_video_activity_patterns_video_age_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='enhanced_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='향상된 메타데이터'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_captions',
            field=models.JSONField(blank=True, default=list, help_text='프레임별 캡션'),
        ),
        migrations.AddField(
            model_name='video',
            name='semantic_tags',
            field=models.JSONField(blank=True, default=list, help_text='의미적 태그'),
        ),
    ]
