# Generated by Django 4.2.18 on 2025-10-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_video_scene_scene_analysis_semantic_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sceneanalysis',
            name='scene',
        ),
        migrations.DeleteModel(
            name='SemanticEmbedding',
        ),
        migrations.AlterUniqueTogether(
            name='videoscene',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='enhanced_metadata',
        ),
        migrations.RemoveField(
            model_name='video',
            name='frame_captions',
        ),
        migrations.RemoveField(
            model_name='video',
            name='semantic_tags',
        ),
        migrations.DeleteModel(
            name='SceneAnalysis',
        ),
        migrations.DeleteModel(
            name='VideoScene',
        ),
    ]
